# Generated by Django 3.2 on 2021-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg', upload_to='food_pictures'),
        ),
    ]
